name: NVD CVE Update
on:
  schedule:
    - cron: '*/30 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: install vulnhub
        env:
          NPM_CONFIG_PREFIX: "~/.npm-global"
        run: |
          export PATH="$(yarn global bin):$PATH"
          yarn global add @inspektre/vulnhub
      - name: vulnhub
        env:
          NEO4J_DATABASE: ${{secrets.NEO4J_DATABASE}}
          NEO4J_PASSWORD: ${{secrets.NEO4J_PASSWORD}}
          NEO4J_URI: ${{secrets.NEO4J_URI}}
          NEO4J_USER: ${{secrets.NEO4J_USER}}
          WORK_DIR: $GITHUB_WORKSPACE/feeds/cve
        run: |
          mkdir -p $GITHUB_WORKSPACE/feeds/cve
          ~/.npm-global/bin/vulnhub download
          ~/.npm-global/bin/vulnhub extract
          ~/.npm-global/bin/vulnhub seed -e
