name: vulnhub-release

on:
  pull_request:
    branches: [main]

jobs:
  vulnhub-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
          package: ./package.json
          tag: "latest"
          check-version: true
      - name: publish-remote-updates
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        run: |
          yarn global add oclif @oclif/dev-cli
          yarn install
          yarn oclif-dev pack && yarn oclif-dev publish
      - name: publish-windows-releases
        run: yarn win
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/win/vulnhub-v*-x64.exe
            dis/win/vulnhub-v*-x86.exe
            LICENSE
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: publish-macos-releases
        run: yarn macos
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/macos/vulnhub-*.pkg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: publish-debian-releases
        run: yarn deb
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/win/vulnhub-v*-deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      